# Projeto Pokemon

## Coletando os dados para o Pandas

In [2]:
import pandas as pd                   #importando a biblioteca com o nome de pd
df = pd.read_csv("pokemon_data.csv")  #importando o arquivo csv como um Dataframe, formato da própria bilbioteca
                                      # usei csv porque é como os dados estão mas poderia ter usado separado por tabulação, o que precisaria de um delimitador
                                      # seria df = pd.read_csv("pokemon_data.txt", delimiter = "\t") sendo "\t" o delimitador
df.head()                             #imprimindo o cabeçalho com os 5 primeiros itens.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

## lendo os dados no Pandas

In [3]:
df.columns #retorna os cabeçalhos, os titulos das colunas como uma lista eu acho.

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [4]:
df["Name"] #retorna a coluna completa informada

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object

In [5]:
df[df.columns[3]] # sim, df.columns retorna uma lista que pode ser acessada dessa forma.

0      Poison
1      Poison
2      Poison
3      Poison
4         NaN
        ...
795     Fairy
796     Fairy
797     Ghost
798      Dark
799     Water
Name: Type 2, Length: 800, dtype: object

In [6]:
df.iloc[1] #retorna a linha específicada com o cabesalho à esquerda.

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [7]:
df.iloc[1:4] #funciona com mais de uma linha em sequencia

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [8]:
df.iloc[1,1] #da pra acessar a celula específica assim, com dois parametros.

'Ivysaur'

In [9]:
df.loc[df["Type 1"]=="Fire"] #filtar as linhas para me retornar apenas as que o tipo 1 seja fogo.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
42,37,Vulpix,Fire,NaN,38,41,40,50,65,65,1,False
43,38,Ninetales,Fire,NaN,73,76,75,81,100,100,1,False
63,58,Growlithe,Fire,NaN,55,70,45,70,50,60,1,False
64,59,Arcanine,Fire,NaN,90,110,80,100,80,95,1,False
83,77,Ponyta,Fire,NaN,50,85,55,65,65,90,1,False
84,78,Rapidash,Fire,NaN,65,100,70,80,80,105,1,False
135,126,Magmar,Fire,NaN,65,95,57,100,85,93,1,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False
158,146,Moltres,Fire,Flying,90,100,90,125,85,90,1,True
169,155,Cyndaquil,Fire,NaN,39,52,43,60,50,65,2,False
170,156,Quilava,Fire,NaN,58,64,58,80,65,80,2,False
171,157,Typhlosion,Fire,NaN,78,84,78,109,85,100,2,False
236,218,Slugma,Fire,NaN,40,40,40,70,40,20,2,False
237,219,Magcargo,Fire,Rock,50,50,120,80,80,30,2,False
259,240,Magby,Fire,NaN,45,75,37,70,55,83,2,False
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
276,255,Torchic,Fire,NaN,45,60,40,70,50,45,3,False
277,256,Combusken,Fire,Fighting,60,85,60,85,60,55,3,False
278,257,Blaziken,Fire,Fighting,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
352,322,Numel,Fire,Ground,60,60,40,65,45,35,3,False
353,323,Camerupt,Fire,Ground,70,100,70,105,75,40,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
355,324,Torkoal,Fire,NaN,70,85,140,85,70,20,3,False
435,390,Chimchar,Fire,NaN,44,58,44,58,44,61,4,False
436,391,Monferno,Fire,Fighting,64,78,52,78,52,81,4,False
437,392,Infernape,Fire,Fighting,76,104,71,104,71,108,4,False
518,467,Magmortar,Fire,NaN,75,95,67,125,95,83,4,False
542,485,Heatran,Fire,Steel,91,90,106,130,106,77,4,True
557,498,Tepig,Fire,NaN,65,63,45,45,45,45,5,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
559,500,Emboar,Fire,Fighting,110,123,65,100,65,65,5,False
572,513,Pansear,Fire,NaN,50,53,48,53,48,64,5,False
573,514,Simisear,Fire,NaN,75,98,63,98,63,101,5,False
614,554,Darumaka,Fire,NaN,70,90,45,15,45,50,5,False
615,555,DarmanitanStandard Mode,Fire,NaN,105,140,55,30,55,95,5,False
616,555,DarmanitanZen Mode,Fire,Psychic,105,30,105,140,105,55,5,False
692,631,Heatmor,Fire,NaN,85,97,66,105,66,65,5,False
721,653,Fennekin,Fire,NaN,40,45,40,62,60,60,6,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
723,655,Delphox,Fire,Psychic,75,69,72,114,100,104,6,False
730,662,Fletchinder,Fire,Flying,62,73,55,56,52,84,6,False
731,663,Talonflame,Fire,Flying,78,81,71,74,69,126,6,False
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [10]:
# df.loc[df["Type 1"]=="Fire" or df["Type 2"]=="flying"] # aparentemende não funciona

## Descrevendo e arrumando dados.

In [11]:
df.describe() #retorna valores como contagem, media, mediana, minimo, maximo, e quartis.

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [12]:
df.sort_values("Name", ascending=False) #ordena os dados, o segundo parâmetro faz ele ficar descendente

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [13]:
df.sort_values(["Name", "HP"], ascending=[1,0]) #ordena baseado em dois fatores, nome ascendente e hp descendente

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

## Mudando os dados

In [14]:
df["Total"] = df["HP"] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]
df
# cria uma coluna com as somas dos valores do pokemon

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [15]:
df = df.drop(columns=["Total"])
df
# elimina a coluna criada

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

## Nota Mental - Evite usar ranges, use os nomes que é mais seguro

In [23]:
#outra forma de fazer isso = vid 22:14  - https://www.youtube.com/watch?v=vmEHCJofslg&t=506s
df['Total'] = df.iloc[:,4:10].sum(axis=1) 

#df['total'] = - segue igual a forma anterior
#df.iloc[:, - usa a função iloc para formar a coluna, os : sem nada significa tudo.
#4:10] nesse caso seria da 4 coluna até a 9 mas o python para uma antes.
#.sum soma
#(axis = 1) - soma horizontalmente se fosse axis=0 somaria verticalmente.

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

## mudando as colunas de lugar

In [24]:
df = df[['#','Name','Type 1', 'Type 2', 'HP','Attack','Defense','Sp. Atk','Sp. Def','Speed','Total','Generation','Legendary']]
df
#mais seguro, porém mais chato, se tivesse muitas colunas seria esquisito fazer dessa forma

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,318,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,405,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,525,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,625,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,309,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,600,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,700,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,600,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,680,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,600,6,True

In [25]:
cols = list(df.columns.values)
df = df[cols[0:4]+ [cols[-1]]+cols[4:12]] #mais fácil, porem, arriscado
df

,#,Name,Type 1,Type 2,Legendary,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Total,Generation
0,1,Bulbasaur,Grass,Poison,False,45,49,49,65,65,45,318,1
1,2,Ivysaur,Grass,Poison,False,60,62,63,80,80,60,405,1
2,3,Venusaur,Grass,Poison,False,80,82,83,100,100,80,525,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,80,100,123,122,120,80,625,1
4,4,Charmander,Fire,NaN,False,39,52,43,60,50,65,309,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,True,50,100,150,100,150,50,600,6
796,719,DiancieMega Diancie,Rock,Fairy,True,50,160,110,160,110,110,700,6
797,720,HoopaHoopa Confined,Psychic,Ghost,True,80,110,60,150,130,70,600,6
798,720,HoopaHoopa Unbound,Psychic,Dark,True,80,160,60,170,130,80,680,6
799,721,Volcanion,Fire,Water,True,80,110,120,130,90,70,600,6

## Salvando .csv

In [26]:
df.to_csv('modificado.csv') #slva com o index criado pelo dataframe

In [27]:
df.to_csv('modificado_sem_index.csv', index=False) #salva sem o index

## Filtrando dados

In [12]:
df.loc[(df['Type 1'] == 'Grass') & (df['HP'] > 78)] 
#lembrar de colocar em parenteses aqui ele mostra os grama com vida acima de 78
new_df = df.loc[(df['Type 1'] == 'Grass') & (df['HP'] > 78)] 
#crio um df novo apenas com o filtro
new_df = new_df.reset_index(drop = True)
#desta forma o novo df cria uma nova coluna de index o parametro apaga o index antigo
# da pra fazer sem atribuir o df na forma de new_df.reset_index(drop = True, inplace = True)
new_df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
1,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
2,71,Victreebel,Grass,Poison,80,105,65,100,70,70,1,False
3,103,Exeggutor,Grass,Psychic,95,95,85,125,65,55,1,False
4,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
5,275,Shiftry,Grass,Dark,90,100,60,90,60,80,3,False
6,357,Tropius,Grass,Flying,99,68,83,72,87,51,3,False
7,389,Torterra,Grass,Ground,95,109,105,75,85,56,4,False
8,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
9,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
10,465,Tangrowth,Grass,NaN,100,100,125,110,50,50,4,False
11,492,ShayminLand Forme,Grass,NaN,100,100,100,100,100,100,4,True
12,492,ShayminSky Forme,Grass,Flying,100,103,75,120,75,127,4,True
13,591,Amoonguss,Grass,Poison,114,85,70,85,80,30,5,False
14,640,Virizion,Grass,Fighting,91,90,72,90,129,108,5,True
15,652,Chesnaught,Grass,Fighting,88,107,122,74,75,64,6,False
16,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False

In [14]:
df.loc[df['Name'].str.contains('Mega')] 
#aqui eu busco tudo que no nome tem mega, eu posso negar isso com ~

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
71,65,AlakazamMega Alakazam,Psychic,NaN,55,50,65,175,95,150,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
102,94,GengarMega Gengar,Ghost,Poison,60,65,80,170,95,130,1,False
124,115,KangaskhanMega Kangaskhan,Normal,NaN,105,125,100,60,100,100,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
168,154,Meganium,Grass,NaN,80,82,100,83,100,80,2,False
196,181,AmpharosMega Ampharos,Electric,Dragon,90,95,105,165,110,45,2,False
224,208,SteelixMega Steelix,Steel,Ground,75,125,230,55,95,30,2,False
229,212,ScizorMega Scizor,Bug,Steel,70,150,140,65,100,75,2,False
232,214,HeracrossMega Heracross,Bug,Fighting,80,185,115,40,105,75,2,False
248,229,HoundoomMega Houndoom,Dark,Fire,75,90,90,140,90,115,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
275,254,SceptileMega Sceptile,Grass,Dragon,70,110,75,145,85,145,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,80,160,80,130,80,100,3,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False
306,282,GardevoirMega Gardevoir,Psychic,Fairy,68,85,65,165,135,100,3,False
327,302,SableyeMega Sableye,Dark,Ghost,50,85,125,85,115,20,3,False
329,303,MawileMega Mawile,Steel,Fairy,50,105,125,55,95,50,3,False
333,306,AggronMega Aggron,Steel,NaN,70,140,230,60,80,50,3,False
336,308,MedichamMega Medicham,Fighting,Psychic,60,100,85,80,85,100,3,False
339,310,ManectricMega Manectric,Electric,NaN,70,75,80,135,80,135,3,False
349,319,SharpedoMega Sharpedo,Water,Dark,70,140,70,110,65,105,3,False
354,323,CameruptMega Camerupt,Fire,Ground,70,120,100,145,105,20,3,False
366,334,AltariaMega Altaria,Dragon,Fairy,75,110,110,110,105,80,3,False
387,354,BanetteMega Banette,Ghost,NaN,64,165,75,93,83,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
397,362,GlalieMega Glalie,Ice,NaN,80,120,80,120,80,100,3,False
409,373,SalamenceMega Salamence,Dragon,Flying,95,145,130,120,90,120,3,False
413,376,MetagrossMega Metagross,Steel,Psychic,80,145,150,105,110,110,3,False
418,380,LatiasMega Latias,Dragon,Psychic,80,100,120,140,150,110,3,True
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
476,428,LopunnyMega Lopunny,Normal,Fighting,65,136,94,54,96,135,4,False
494,445,GarchompMega Garchomp,Dragon,Ground,108,170,115,120,95,92,4,False
498,448,LucarioMega Lucario,Fighting,Steel,70,145,88,140,70,112,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
527,475,GalladeMega Gallade,Psychic,Fighting,68,165,95,65,115,110,4,False
591,531,AudinoMega Audino,Normal,Fairy,103,60,126,80,126,50,5,False
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

In [15]:
import re

df.loc[df['Type 1'].str.contains('fire|grass', flags=re.I, regex=True)] 
#aqui ele procura linhas que o tipo 1 seja fire ou grass mas perceba que usamos dentro da string, isso graças a essa biblioteca.
# a expressão regex=True habilita procurar dessa forma
# a expressão flags=re.I faz a procura ignorar letras maiúsculas.
# o sinal | representa ou.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
735,667,Litleo,Fire,Normal,62,50,58,73,54,72,6,False
736,668,Pyroar,Fire,Normal,86,68,72,109,66,106,6,False
740,672,Skiddo,Grass,NaN,66,65,48,62,57,52,6,False
741,673,Gogoat,Grass,NaN,123,100,62,97,81,68,6,False
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [16]:
df.loc[df['Name'].str.contains('^pi[a-z]*', flags=re.I, regex=True)] 
# aqui ele procura nomes que começam com pi
# o ^ informa que a procura tem que começar com as letras especificadas
# o [a-z] informa que pode ser qualquer letra depois de pi
# * informa que pode incluir nada

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,50,55,50,36,30,43,5,False

## Mudanças condicionais

In [17]:
df.loc[df['Type 1'] == 'Fire', 'Type 1'] = 'Flamer'
df
#aqui ele muda os fogo pra flamer, eu poderia mudar os fogos pra lendarios na forma de 
# df['Type 1'] == 'Fire', 'Legendary'] = True
#agora todos os fogo seriam lendários

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,6,True

In [18]:
df.loc[df['HP']>70, ['Generation', 'Legendary']] = ['personalizada' , 'verdade']
df
# eu posso mudar mais de uma coluna baseada em outra

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,personalizada,verdade
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,personalizada,verdade
4,4,Charmander,Flamer,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,personalizada,verdade
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,personalizada,verdade
799,721,Volcanion,Flamer,Water,80,110,120,130,90,70,personalizada,verdade